### ISSUE TITLE
Kafka manager does not show that the consumer type is KF

### ISSUE THREAD

**Issue by rr2yy** [yahoo/CMAK#557]
- kafka1.1.0

- kafkaManage1.3.3.18

![image](https://user-images.githubusercontent.com/27758325/44654895-e5294880-aa25-11e8-9c8d-2eb39942bf69.png)
The corresponding parameters have been configured
![image](https://user-images.githubusercontent.com/27758325/44654964-17d34100-aa26-11e8-8a23-116c460fc769.png)

**Comment by jsargiot** [comment]
Hi @moranyuwen, can you give us a bit more info about your cluster? Is it using some sort of SSL configuration?

Are there any exception in Kafka Manager's output?

**Comment by moranyuwen** [comment]
No SSL configuration is used
