### ISSUE TITLE
support change replication factor

### ISSUE THREAD

**Issue by danielmotaleite** [yahoo/CMAK#650]
We can increase or lower the replication factor using this method:

https://www.allprogrammingtutorials.com/tutorials/changing-replication-factor-of-topic-in-kafka.php

kafka-manager could do this in a mostly automatic way for the user

**Comment by uriinf** [comment]
For those who is still looking for  topic replication change:

<img width="1319" alt="1" src="https://user-images.githubusercontent.com/18531314/189115886-732ac46e-19c0-4ae7-90cb-86ed76c7e17c.png">

<img width="626" alt="2" src="https://user-images.githubusercontent.com/18531314/189115943-b577d3ea-bf85-40c4-8d81-26295c6c8b75.png">

<img width="1213" alt="3" src="https://user-images.githubusercontent.com/18531314/189116005-68cab7a0-e4c5-43db-8cbd-58e95e1ae1c5.png">

<img width="722" alt="4" src="https://user-images.githubusercontent.com/18531314/189116035-8f8b219f-ba71-4091-aaee-42ae39bdedf9.png">

<img width="1177" alt="5" src="https://user-images.githubusercontent.com/18531314/189116057-993f08b9-4139-44d3-ab01-9e18be5d66fe.png">

**Comment by danielmotaleite** [comment]
yes, i had tried that, but didn't noticed that after the "try force running" warning, the "reassign partitions" did change to force.

Thanks for the info, very useful, i will try that later on
