### ISSUE TITLE
Build fails under Java 11

### ISSUE THREAD

**Issue by dlozinski** [yahoo/CMAK#721]
error] CMAK/app/kafka/manager/actor/cluster/KafkaStateActor.scala:102:19: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]       cp => props.putAll(cp)

**Comment by patelh** [comment]
Use latest release.
