### ISSUE TITLE
./sbt: line 241: 31029 Killed 

### ISSUE THREAD

**Issue by Lorryrui** [yahoo/CMAK#734]
os: CentOS Linux release 7.7.1908 ; 1core 1gb
openjdk version "11.0.6" 2020-01-14 LTS

[info] Main Scala API documentation successful.
[info] Compiling 133 Scala sources and 2 Java sources to /tmp/CMAK-3.0.0.1/target/scala-2.12/classes ...
./sbt: line 241: 31029 Killed                  "$@"

need some help.

**Comment by patelh** [comment]
Release 3.0.0.2 has compiled binary attached as asset.

**Comment by Lorryrui** [comment]
> Release 3.0.0.2 has compiled binary attached as asset.

thks
