### ISSUE TITLE
Need disabled KafkaManagedOffsetCache on CMAK

### ISSUE THREAD

**Issue by rodrigongarcia** [yahoo/CMAK#759]
Hi,
I need disabled KafkaManagedOffsetCache, from doc:
> Kafka managed consumer offset is now consumed by KafkaManagedOffsetCache from the "__consumer_offsets" topic. Note, this has not been tested with large number of offsets being tracked. There is a single thread per cluster consuming this topic so it may not be able to keep up on large # of offsets being pushed to the topic.

i have a lots of timeouts becouse this:
```
2020-04-02 15:55:10,608 - [ERROR] k.m.a.c.KafkaStateActor - consumerProperties:{key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer, security.protocol=PLAINTEXT, metric.reporters=kafka.manager.actor.cluster.NoopJMXReporter, value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer, group.id=kafka.manager.actor.cluster.KafkaStateActor.KafkaTopicOffsetGetter, bootstrap.servers=kafka-broker-01:9092}
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 30003ms
2020-04-02 15:55:10,608 - [ERROR] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception 
```

later i have issues on kafka brokers and correlations id:
```
java.lang.IllegalStateException: Correlation id for response (1871115) does not match request (1871104)
Sample stack trace
       org.apache.kafka.clients.NetworkClient.correlate (NetworkClient.java:477)
…he.kafka.clients.NetworkClient.handleCompletedReceives (NetworkClient.java:440)
            org.apache.kafka.clients.NetworkClient.poll (NetworkClient.java:265)
 org.apache.kafka.clients.producer.internals.Sender.run (Sender.java:216)
 org.apache.kafka.clients.producer.internals.Sender.run (Sender.java:128)
                                   java.lang.Thread.run (Thread.java:748)
```
My analisis and i see to many onfly messages, that is for the stress of this actor: KafkaTopicOffsetGetter trying get the metadata and offsets.

Thx a lot, sry for my bad english :)

**Comment by rodrigongarcia** [comment]
i update to kafka 2.4.1 and fix the problem.

**Comment by poyyi** [comment]
i'm running to same problem with cmak=3.0.0.4; kafka version=2.3.1
in the cmak dropdown for kafka version support there is no 2.3.0  series will this not support 2.3.1 ?
Is there any resolution without upgrading to 2.4.1
coz of it is not showing any Lags on consumers "Lag unavailable lag"
Thanks

**Comment by poyyi** [comment]
i'm running to same problem with cmak=3.0.0.4; kafka version=2.3.1
in the cmak dropdown for kafka version support there is no 2.3.0  series will this not support 2.3.1 ?
Is there any resolution without upgrading to 2.4.1
coz of it is not showing any Lags on consumers "Lag unavailable lag"
Thanks

**Comment by poyyi** [comment]
i'm running to same problem with cmak=3.0.0.4; kafka version=2.3.1
in the cmak dropdown for kafka version support there is no 2.3.0  series will this not support 2.3.1 ?
Is there any resolution without upgrading to 2.4.1
coz of it is not showing any Lags on consumers "Lag unavailable lag"
Thanks

**Comment by poyyi** [comment]
i'm running to same problem with cmak=3.0.0.4; kafka version=2.3.1
in the cmak dropdown for kafka version support there is no 2.3.0  series will this not support 2.3.1 ?
Is there any resolution without upgrading to 2.4.1
coz of it is not showing any Lags on consumers "Lag unavailable lag"
Thanks
