### ISSUE TITLE
What "Under Replicated?" in topic view means? 

### ISSUE THREAD

**Issue by MikeAtiwat** [yahoo/CMAK#797]
I work with 4 brokers and try to monitor the replication of the topic.
In my understand the insync replicas means that the replica is up to date. And the "Under replicated?" means the topic is now all replicated. but it seems opposite because when I got all in sync replica the "Under replicated?" shows the result "False" but when I got only one in sync the "Under replicated?" shows the result "True". So, what "Under Replicated?" in topic view means? 
<img width="1389" alt="Screen Shot 2563-09-09 at 11 41 43" src="https://user-images.githubusercontent.com/46403195/92556127-58abf480-f293-11ea-92e8-6662aca1dab2.png">

Thank you.

**Comment by hiralsp** [comment]
When the # of replicas and in sync replicas match, then it's not under replicated.

**Comment by MikeAtiwat** [comment]
> When the # of replicas and in sync replicas match, then it's not under replicated.
Thank you hiralsp. Now I got the idea of it.
