### ISSUE TITLE
./sbt clean dist   An error occurred

### ISSUE THREAD

**Issue by lxri** [yahoo/CMAK#802]
[info] Loading settings for project cmak-build from plugins.sbt ...
[info] Loading project definition from /opt/cmak/CMAK/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to cmak (in build file:/opt/cmak/CMAK/)
[success] Total time: 0 s, completed Oct 14, 2020 12:38:21 AM
[info] Wrote /opt/cmak/CMAK/target/scala-2.12/cmak_2.12-3.0.0.5.pom
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Main Scala API documentation to /opt/cmak/CMAK/target/scala-2.12/api...
[info] Compiling 136 Scala sources and 2 Java sources to /opt/cmak/CMAK/target/scala-2.12/classes ...
[error] /opt/cmak/CMAK/app/kafka/manager/actor/cluster/KafkaStateActor.scala:115:29: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]       cp => props.putAll(cp.asMap)
[error]                             ^
[error] /opt/cmak/CMAK/app/kafka/manager/actor/cluster/KafkaStateActor.scala:275:29: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]       cp => props.putAll(cp.asMap)
[error]                             ^
[error] /opt/cmak/CMAK/app/kafka/manager/actor/cluster/KafkaStateActor.scala:115:29: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]       cp => props.putAll(cp.asMap)
[error]                             ^
[error] /opt/cmak/CMAK/app/kafka/manager/actor/cluster/KafkaStateActor.scala:275:29: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]       cp => props.putAll(cp.asMap)
[error]                             ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/logkafka81/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/logkafka82/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/logkafka81/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/logkafka82/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero10/LogConfig.scala:312:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_,_]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero10/LogConfig.scala:313:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero11/LogConfig.scala:272:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_, _]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero11/LogConfig.scala:273:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero81/LogConfig.scala:118:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero82/LogConfig.scala:184:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero90/LogConfig.scala:176:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_, _]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero90/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero10/LogConfig.scala:312:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_,_]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero10/LogConfig.scala:313:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero11/LogConfig.scala:272:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_, _]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero11/LogConfig.scala:273:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero81/LogConfig.scala:118:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero82/LogConfig.scala:184:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero90/LogConfig.scala:176:39: type mismatch;
[error]  found   : java.util.Map[_$5,_$6] where type _$6, type _$5
[error]  required: java.util.Map[_ <: Object, _ <: Object]
[error]     props.putAll(defaults.asInstanceOf[java.util.Map[_, _]])
[error]                                       ^
[error] /opt/cmak/CMAK/app/kafka/manager/utils/zero90/LogConfig.scala:177:28: type mismatch;
[error]  found   : java.util.Map[_$1,_$2] where type _$2, type _$1
[error]  required: java.util.Map[? <: Object, ? <: Object]
[error] Note: _$1 >: ? <: Object, but Java-defined trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error] Note: _$2 >: ? <: Object, but Java-defined trait Map is invariant in type V.
[error] You may wish to investigate a wildcard type such as `_ >: ? <: Object`. (SLS 3.2.10)
[error]     props.putAll(overrides.asMap)
[error]                            ^
[error] 12 errors found
[info] LESS compiling on 1 source(s)
[info] No documentation generated with unsuccessful compiler run
[error] 12 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] (Compile / doc) Scaladoc generation failed

**Comment by lxri** [comment]
CentOS Linux release 7.7
kafka-2.4.0 
use zookeeper Comes with kafka  and I modified the zookeeper address in the configuration file

**Comment by lxri** [comment]
solved

**Comment by connorworkman** [comment]
@lxri What was the solution?
I'm hitting the same issue. I might have run into this on a previous build but I'm not remembering any solution.
