### ISSUE TITLE
CMAK cluster configuration

### ISSUE THREAD

**Issue by faabsen** [yahoo/CMAK#831]
After looking up the documentation and the code it should be possible to define a cluster when starting the application. 
However, the automatic load of the configuration does not work as expected: every cluster has to be configured manually after the application has loaded. 

Is there a way to define (multiple) cluster via the config file? If so, how? Or is this only possible via the (REST) API after the application has started successfully?

Is there a chance that Kafka 2.7.0 will be supported out of the box?

Cheers!

**Comment by eshepelyuk** [comment]
Yes only possible via REST for now. See #244 for some workarounds.

**Comment by eshepelyuk** [comment]
@faabsen you may also check [cmak2zk](https://github.com/eshepelyuk/cmak-operator#standalone-cmak2zk-tool) tool I've release recently.

**Comment by faabsen** [comment]
> Yes only possible via REST for now. See #244 for some workarounds.

Thanks 👍 . Already checked on this.

> @faabsen you may also check [cmak2zk](https://github.com/eshepelyuk/cmak-operator#standalone-cmak2zk-tool) tool I've release recently.

Will definitly have a look at it tomorrow!
