### ISSUE TITLE
What does "disable cluster" actually means?

### ISSUE THREAD

**Issue by Aracki** [yahoo/CMAK#840]
![image](https://user-images.githubusercontent.com/6129986/117125213-881aee80-ad99-11eb-9de1-3a8f0e30452c.png)

Cannot find reference in CMAK's docs about what this button actually means?

**Comment by eshepelyuk** [comment]
It will keep cluster configured in CMAK settings storage (ZK) but

* You cant see any data from UI, cluster is non clickable
* No polling for metrics or consumer lags is peformed

**Comment by Aracki** [comment]
Thanks for the answer @eshepelyuk
