### ISSUE TITLE
Suggest adding functions:the management and maintenance of zookeeper 

### ISSUE THREAD

**Issue by Jacky-cn** [yahoo/CMAK#904]
Management and maintenance of kafka and other related configurations, parameters, nodes and other information stored in zookeeper, which is also convenient for management and maintenance in one interface。
Is this feature planned now? When will it be realized?

**Comment by OneCricketeer** [comment]
Given that Zookeeper is being removed from Kafka altogether, I'd recommend finding alternative tools for managing Zookeeper.
